export const getIntervalsData = () => ([
  // { id: 1, name: ['Прима'] },
  { id: 2, number: '0.5', name: ['Секунда', 'малая'] },
  { id: 3, number: '1', name: ['Секунда', 'большая'] },
  { id: 4, number: '1.5', name: ['Терция', 'малая'] },
  { id: 5, number: '2', name: ['Терция', 'большая'] },
  { id: 6, number: '2.5', name: ['Кварта'] },
  { id: 7, number: '3', name: ['Тритон'] },
  { id: 8, number: '3.5', name: ['Квинта'] },
  { id: 9, number: '4', name: ['Секста', 'малая'] },
  { id: 10, number: '4.5', name: ['Секста', 'большая'] },
  { id: 11, number: '5', name: ['Септима', 'малая'] },
  { id: 12, number: '5.5', name: ['Септима', 'большая'] },
  { id: 13, number: '6', name: ['Октава'] },
]);
